### PR TITLE
Features/notice and consent b

### PR DESCRIPTION
**Pull request by HotEmu**
Added a new feature to Discovery Service that allows users to view the "Notice and Consent" under the discovery service input field. Powered by a separate stylesheet that will be utilized by the stand-alone Notice and Consent page in the future. 

Screen Shot 2020-06-25 at 11 16 15 PM

### CODE REVIEW

**Comment by leifj** [comment]
Does the checkbox do anything currently? I can't see it tied to anything in the code.

**Comment by leifj** [comment]
also the netlify preview doesn't actually work...

**Comment by HotEmu** [comment]
@leifj the checkbox doesn't do anything, I don't know exactly what to do with it yet, this was purely front-end implementation.

**Comment by HotEmu** [comment]
@leifj I just noticed the netlify preview issues, I'm getting a 404 in the console log, not sure what the problem is.

**Comment by leifj** [comment]
@HotEmu I have implemented the business logic for opt-out. One thing to fix: the variable @media-driven sizing for the search panel is nice but the text string truncation needs to match the width!

**Pull request merged**
